In [ ]:
# Import the modules
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.metrics import balanced_accuracy_score, confusion_matrix, classification_report

---

## Split the Data into Training and Testing Sets

### Step 1: Read the `lending_data.csv` data into a Pandas DataFrame.

In [ ]:
# Read the CSV file into a Pandas DataFrame
lendingDF = pd.read_csv("lending_data.csv")

# Review the DataFrame
lendingDF.head()

loan_size  interest_rate  borrower_income  debt_to_income  num_of_accounts  \
0    10700.0          7.672            52800        0.431818                5   
1     8400.0          6.692            43600        0.311927                3   
2     9000.0          6.963            46100        0.349241                3   
3    10700.0          7.664            52700        0.430740                5   
4    10800.0          7.698            53000        0.433962                5   

   derogatory_marks  total_debt  loan_status  
0                 1       22800            0  
1                 0       13600            0  
2                 0       16100            0  
3                 1       22700            0  
4                 1       23000            0

### Step 2: Create the labels set (`y`)  from the “loan_status” column, and then create the features (`X`) DataFrame from the remaining columns.

In [ ]:
# Separate the data into labels and features

# Separate the y variable, the labels - use loan_status column
y = lendingDF["loan_status"]

# Separate the X variable, the features - use the remaining columns (use .drop)
X = lendingDF.drop(columns="loan_status")

In [ ]:
# Review the y variable Series
y[:5]

0    0
1    0
2    0
3    0
4    0
Name: loan_status, dtype: int64

In [ ]:
# Review the X variable DataFrame
X[:5]

loan_size  interest_rate  borrower_income  debt_to_income  num_of_accounts  \
0    10700.0          7.672            52800        0.431818                5   
1     8400.0          6.692            43600        0.311927                3   
2     9000.0          6.963            46100        0.349241                3   
3    10700.0          7.664            52700        0.430740                5   
4    10800.0          7.698            53000        0.433962                5   

   derogatory_marks  total_debt  
0                 1       22800  
1                 0       13600  
2                 0       16100  
3                 1       22700  
4                 1       23000

### Step 3: Check the balance of the labels variable (`y`) by using the `value_counts` function.

In [ ]:
# Check the balance of our target values
y.value_counts()

0    75036
1     2500
Name: loan_status, dtype: int64

### Step 4: Split the data into training and testing datasets by using `train_test_split`.

In [ ]:
# Import the train_test_learn module
from sklearn.model_selection import train_test_split

# Split the data using train_test_split
# Assign a random_state of 1 to the function
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state=1)

---

## Create a Logistic Regression Model with the Original Data

###  Step 1: Fit a logistic regression model by using the training data (`X_train` and `y_train`).

In [ ]:
# Import the LogisticRegression module from SKLearn
from sklearn.linear_model import LogisticRegression

# Instantiate the Logistic Regression model
# Assign a random_state parameter of 1 to the model
logModel = LogisticRegression(solver= 'lbfgs', random_state=1)
#logModel
# Fit the model using training data
logModel.fit(X_train,y_train)

LogisticRegression(random_state=1)

### Step 2: Save the predictions on the testing data labels by using the testing feature data (`X_test`) and the fitted model.

In [ ]:
# Make a prediction using the testing data
predictions = logModel.predict(X_test)

# dataframe with the actuals vs the predicted values
pd.DataFrame(
    {
        "Actuals": y_test,
        "Predictions": predictions,
    }
).head(12)

Actuals  Predictions
60914        0            0
36843        0            0
1966         0            0
70137        0            0
27237        0            0
40013        0            0
43107        0            0
61988        0            0
57437        0            0
46757        0            0
76181        1            1
28403        0            0

### Step 3: Evaluate the model’s performance by doing the following:

* Calculate the accuracy score of the model.

* Generate a confusion matrix.

* Print the classification report.

In [ ]:
# Print the balanced_accuracy score of the model
logModel.score(X_train, y_train)

0.9921240885954051

In [ ]:
logModel.score(X_test, y_test)

0.9918489475856377

In [ ]:
# Generate a confusion matrix for the model
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, predictions)

array([[18663,   102],
       [   56,   563]])

In [ ]:
# Print the classification report for the model
from sklearn.metrics import classification_report

print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       1.00      0.99      1.00     18765
           1       0.85      0.91      0.88       619

    accuracy                           0.99     19384
   macro avg       0.92      0.95      0.94     19384
weighted avg       0.99      0.99      0.99     19384



### Step 4: Answer the following question.

**Question:** How well does the logistic regression model predict both the `0` (healthy loan) and `1` (high-risk loan) labels?

**Answer:** The logistic regression model does well in precision for the healthy loans at 100% and the high-risk loans at 85%- of course, the 100% is what we want to see. Recall is at 99% for healthy loans and 91% for high risk loans, so positive cases caught for both loan instances. As for the f1 scores, healthy loans have an ideal score of 100%, followed by high risk loans at a score of 88%. So, overall we see the logistic regression model predicting our data well.

---

## Predict a Logistic Regression Model with Resampled Training Data

### Step 1: Use the `RandomOverSampler` module from the imbalanced-learn library to resample the data. Be sure to confirm that the labels have an equal number of data points.

In [ ]:
# Import the RandomOverSampler module form imbalanced-learn
from imblearn.over_sampling import RandomOverSampler

# Instantiate the random oversampler model
# # Assign a random_state parameter of 1 to the model
randModel = RandomOverSampler(random_state=1)

# Fit the original training data to the random_oversampler model
X_resampled, y_resampled = randModel.fit_resample(X_train,y_train)

In [ ]:
# Count the distinct values of the resampled labels data
y_resampled

0         0
1         0
2         0
3         0
4         0
         ..
112537    1
112538    1
112539    1
112540    1
112541    1
Name: loan_status, Length: 112542, dtype: int64

### Step 2: Use the `LogisticRegression` classifier and the resampled data to fit the model and make predictions.

In [80]:
# Instantiate the Logistic Regression model
# Assign a random_state parameter of 1 to the model
resampLogModel= LogisticRegression(random_state=1)
# Fit the model using the resampled training data
resampLogModel.fit(X_resampled, y_resampled)

# Make a prediction using the testing data
resampPrediction= resampLogModel.predict(X_test)
resampPrediction[:5]

array([0, 0, 0, 0, 0])

In [81]:
# dataframe for resampled predictions
pd.DataFrame(
    {
        "Resampled Actual": y_test,
        "Resampled Prediction": resampPrediction
    }
).head()

Resampled Actual  Resampled Prediction
60914                 0                     0
36843                 0                     0
1966                  0                     0
70137                 0                     0
27237                 0                     0

### Step 3: Evaluate the model’s performance by doing the following:

* Calculate the accuracy score of the model.

* Generate a confusion matrix.

* Print the classification report.

In [82]:
# Print the balanced_accuracy score of the model
resampLogModel.score(X_train, y_train)

0.9945659650570917

In [83]:
resampLogModel.score(X_test, y_test)

0.9938093272802311

In [85]:
# Generate a confusion matrix for the model
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test,resampPrediction)

array([[18649,   116],
       [    4,   615]])

In [87]:
# Print the classification report for the model
from sklearn.metrics import classification_report

print(classification_report(y_test, resampPrediction))

              precision    recall  f1-score   support

           0       1.00      0.99      1.00     18765
           1       0.84      0.99      0.91       619

    accuracy                           0.99     19384
   macro avg       0.92      0.99      0.95     19384
weighted avg       0.99      0.99      0.99     19384



### Step 4: Answer the following question

**Question:** How well does the logistic regression model, fit with oversampled data, predict both the `0` (healthy loan) and `1` (high-risk loan) labels?

**Answer:** We can see that the logistic regression model fits even better with the oversampled data. Well, we generally had ideal precision, recall, and f1 for the healthy loan to start with, and now we see those same percentages carry over with the oversampled data. The high-risk loan labels experienced a general increase in percent, except for the precision, which decreased by 1%. The recall and f1 score on the other hand experienced an 8% and 3% increase, respectively.